DROP DATABASE IF EXISTS db_laboratorio; 

CREATE DATABASE db_laboratorio;

USE db_laboratorio;

CREATE TABLE CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOMBRE_CLIENTE VARCHAR (100) NOT NULL,
EMPRESA VARCHAR (100),
MAIL VARCHAR (100) NOT NULL,
TELEFONO VARCHAR (20)
);

CREATE TABLE MUESTRAS (
ID_MUESTRAS INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
N_ORDEN INT NOT NULL,
ID_CLIENTE INT NOT NULL,
FECHA_RECEPCION DATE NOT NULL,
TIPO_DE_MUESTRA VARCHAR (50) NOT NULL,
PROCEDENCIA VARCHAR (50), 
DESCRIPCION VARCHAR (200),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE DETERMINACIONES (
ID_DETERMINACION INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_MUESTRAS INT NOT NULL, 
NOMBRE VARCHAR (50) NOT NULL,
FOREIGN KEY (ID_MUESTRAS) REFERENCES MUESTRAS (ID_MUESTRAS)
);

CREATE TABLE RESULTADOS (
ID_RESULTADOS INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_DETERMINACION INT NOT NULL,
RESULTADO DECIMAL (7,4),
FOREIGN KEY (ID_DETERMINACION) REFERENCES DETERMINACIONES (ID_DETERMINACION)
);

CREATE TABLE TECNICOS (
ID_TECNICO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR (20),
APELLIDO VARCHAR (20),
ESPECIALIDAD VARCHAR (50),
TELEFONO VARCHAR (20),
ID_DETERMINACION INT NOT NULL,
FOREIGN KEY (ID_DETERMINACION) REFERENCES DETERMINACIONES (ID_DETERMINACION)
);